"""Declarative base and shared mixins for all Z3rno models.

Every tenant-scoped table inherits from ``OrgScopedMixin`` which adds an
``org_id`` column with a foreign key to ``tenants.org_id`` and the cascade
delete behaviour we want for GDPR.

Every table that needs created/updated tracking inherits from ``TimestampMixin``.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import DateTime, ForeignKey, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ----------------------------------------------------------------------------
# Naming convention for indexes / constraints — ensures Alembic autogenerated
# migrations produce stable, predictable names. Without this, Alembic can
# generate different names on different machines.
# ----------------------------------------------------------------------------
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Single declarative base for every Z3rno model.

    All models inherit from this. Alembic env.py imports this Base to access
    ``Base.metadata`` for autogeneration.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds created_at + updated_at server-side timestamps.

    Both columns default to ``NOW()`` on the database side. ``updated_at``
    is updated by an explicit application-side ``onupdate=now()`` so we don't
    rely on database triggers (which would not survive a switch to RDS).
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class OrgScopedMixin:
    """Adds an ``org_id`` foreign key for tenant isolation.

    Every table protected by Row-Level Security inherits this mixin. RLS
    policies created in Week 1 Thursday filter on this column via
    ``current_setting('app.current_org_id')::UUID``. The mixin alone does
    not enable RLS — that is handled separately by the Alembic migration.
    """

    org_id: Mapped[UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("tenants.org_id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
